---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/build-timestamp: 2024-09-20 - 09:02:03 +0000
  labels:
    app.kubernetes.io/name: helm-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: helm-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: helm-quickstart
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.14.4
        app.quarkus.io/build-timestamp: 2024-09-20 - 09:02:03 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: helm-quickstart
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Never
          name: helm-quickstart
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
