apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - repoURL: git@github.com:fernandobalieiro/helm-charts.git
            path: charts/helm-quickstart
            name: helm-quickstart
            type: api
  template:
    metadata:
      name: '{{name}}'
      labels:
        type: '{{type}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
